### ISSUE TITLE
PyPI source package missing nauty's sources/object files

### ISSUE THREAD

**Issue by goens** [pdobsan/pynauty#10]
When installing version 1.0b3 over PyPI, the source distribution will not compile, due to nauty's sources/object files missing:
```
    building 'pynauty.nautywrap' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/src
    creating build/temp.linux-x86_64-3.9/src/pynauty
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc/nauty27r1 -Isrc/pynauty -I/home/goens/.virtualenvs/mocasin/include -I/usr/include/python3.9 -c src/pynauty/nautywrap.c -o build/temp.linux-x86_64-3.9/src/pynauty/nautywrap.o -O4 -fPIC
    In file included from src/pynauty/nautywrap.c:16:
    src/nauty27r1/nauty.h:40: warning: "_FILE_OFFSET_BITS" redefined
       40 | #define _FILE_OFFSET_BITS 0
          |
    In file included from /usr/include/python3.9/pyconfig.h:3,
                     from /usr/include/python3.9/Python.h:8,
                     from src/pynauty/nautywrap.c:15:
    /usr/include/x86_64-linux-gnu/python3.9/pyconfig.h:1578: note: this is the location of the previous definition
     1578 | #define _FILE_OFFSET_BITS 64
          |
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/src/pynauty/nautywrap.o src/nauty27r1/nauty.o src/nauty27r1/nautil.o src/nauty27r1/naugraph.o src/nauty27r1/schreier.o src/nauty27r1/naurng.o -o build/lib.linux-x86_64-3.9/pynauty/nautywrap.cpython-39-x86_64-linux-gnu.so
    x86_64-linux-gnu-gcc: error: src/nauty27r1/nauty.o: No such file or directory
    x86_64-linux-gnu-gcc: error: src/nauty27r1/nautil.o: No such file or directory
    x86_64-linux-gnu-gcc: error: src/nauty27r1/naugraph.o: No such file or directory
    x86_64-linux-gnu-gcc: error: src/nauty27r1/schreier.o: No such file or directory
    x86_64-linux-gnu-gcc: error: src/nauty27r1/naurng.o: No such file or directory
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```
For reference, this happens on Debian sid, Python 3.9.1+, with a virtualenv

**Comment by goens** [comment]
I see two possible options to fix this, either include nauty's sources in the source distribution (using the `packag_data` object in `setup.py`), or shipping binaries directly. I suppose there's a reason why you chose a source package, in that case, the former option might be the better fix.

By the way, just in case you missed it, there's also a test variant of PyPI for testing these setups: https://test.pypi.org/ Thought it might be worth mentioning.

**Comment by pdobsan** [comment]
I am aware of the problem, the reason is not what you think. I also know test.pypi and have been using it. The source distribution does contain nauty's source, what is more [the release](https://pypi.org/project/pynauty/1.0b3/#files) does include both a binary wheel and a source variant, check it. None of your solutions really solves the problem.

What command caused the error message, I guess `pip install pynauty`; next time include the command too. If you follow the readme, and download the source variant *from pypi*, it works of course you need manually build as instructed in the readme.

More importantly, what is the glibc version on this debian system?

Also try `pip install pynauty==1.0b2` I would not be surprised if that "worked", but need to know the result for sure.

**Comment by pdobsan** [comment]
I forgot, there is also a different build on `test.pypi` , could you try that one too:
`pip install -i https://test.pypi.org/simple/ pynauty==1.0b3`

**Comment by pdobsan** [comment]
One more thing to keep in mind as you are experiencing. Try to use the most recent pip, wheel, I guess you already do, for working in a virtaulenv. `pip` does not deal with caching correctly and transparently, as I discovered. I think it might be a bug, I haven't reported yet. The only way, to make sure that you cleared the cache and you have what you see is to delete the cache (`rm -fr ~/.cache/pip/`) between sessions. Otherwise pip is happy to install something else what you intended.

**Comment by goens** [comment]
Yes you're right, I should have included the command itself to reproduce, sorry. I ran the command as in the README: `pip install pynauty`. The 'solutions' were just my first thoughts of options that could fix it, not much more, but if you say they don't solve the issue I'm sure you know what you're talking about.

I can reproduce this with pip-20.1.1 and pip-21.0.1 and wheel-0.34.2 and wheel-0.36.2 (all combinations of these yielded the problem). I also can reproduce with a virtual env and without a virtual env, also after deleting the cache.

**Comment by goens** [comment]
I checked the files on the release, as you recommended. The source release does include the nauty sources, but the binary does not include the nauty sources nor the object files, as per the original issue. This is the output of `wheel2json pynauty-1.0rc4-cp39-cp39-manylinux_2_33_x86_64.whl | grep path`:
```
                "path": "pynauty/__init__.py",
                "path": "pynauty/__main__.py",
                "path": "pynauty/graph.py",
                "path": "pynauty/nautywrap.c",
                "path": "pynauty/nautywrap.cpython-39-x86_64-linux-gnu.so",
                "path": "pynauty/nautywrap.h",
                "path": "pynauty/__pycache__/__init__.cpython-39.pyc",
                "path": "pynauty/__pycache__/graph.cpython-39.pyc",
                "path": "pynauty-1.0rc4.dist-info/COPYING",
                "path": "pynauty-1.0rc4.dist-info/METADATA",
                "path": "pynauty-1.0rc4.dist-info/WHEEL",
                "path": "pynauty-1.0rc4.dist-info/top_level.txt",
                "path": "pynauty-1.0rc4.dist-info/RECORD",
```
It should include the original nauty sources or object files so that it can compile it (or link to it, but that might be less portable). Also, the size of the `.whl` file of 70K is a big tell that something's missing. I'm happy to look into this and see if I can fix that somehow.

**Comment by pdobsan** [comment]
All these expected and intentional, part of my experiencing with how would be the best to publish the package. I removed all but the latest rc4 from (test).pypi.og, this is of course exhibits the same behavior. The condition using the binary wheel is set to very high, it works only if glibc version >= 2.33. On such systems the install works nice and quickly. On older systems (or without wheel) pip will try to install the source version, that fails with the result you have seen.

The solution is to extend the Install method in setup.py with an extra step calling `make nauty-objects` first. That is enough, and that is the fix. You can see that by  running it manually then running `pip install -U .` I have not got around to modify extend setup.py  yet along these lines.

The related documentation is lacking, non existent, out of date and  in flux. There are some examples floating around, but they are based on distutils or a mix of distutils/setuptools. Since I moved over to setuptools I'd like to find the most up to date solution using as much of the new bits of the packaging ecosystem as possible.

You are welcome to take a shot at it. But I will be picky :-)

Meanwhile, I see your other comment, you are mistaken the wheel is fine, see above what really is going on. I hope that makes it clear. Another thing, a source solution must not contain object files!

**Comment by goens** [comment]
> All these are expected and intentional, part of my experiencing with how would be the best to publish the package. I removed all but the latest rc4 from (test).pypi.og, this is of course exhibits the same behavior. The condition using the binary wheel is set to very high, it works only if glibc version >= 2.33. On such systems the install works nice and quickly. On older systems (or without wheel) pip will try to install the source version, that fails with the result you have seen.

I see. Yes, indeed, that's a very new glibc version (released <= 1 month ago), so it will take a while until it's found in many systems,  my glibc is a bit older.

You're right, it does work for me if I do things manually (in this case, just comment out the line in Makefile.dist `@cd dist/ ; ../src/fix-wheel-tag.sh`). I'm curious, what's the reasoning behind this?

> Meanwhile, I see your other comment, you are mistaken the wheel is fine, see above what really is going on. I hope that makes it clear. Another thing, a source solution must not contain object files!

Right, I agree. I meant the object files for the binary build, not the source build. It seems I was mistaken, right, and these are probably included in the pynauty shared object file.

> You are welcome to take a shot at it. But I will be picky :-)

I figured :-) It seems you have the hang of it and it's probably a better use of both our times if I leave you to it (and you don't have to review and change things to the way you like them anyway).

**Comment by pdobsan** [comment]
The title of this issue is misleading, nothing missing. There is no real problem, the user sometimes has to build from sources, that is all. Anyway, setup.py will be extended to reduce work in such cases, and more binary wheels are coming.
Therefore I am closing this issue.
